# -*- coding: utf-8 -*-
"""model webpage.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fqety9x1fwTcLl-4HWetg4Cua_lWOu7F
"""

import numpy as np
import streamlit as st
import cv2
from keras.models import load_model
import tensorflow as tf
model= load_model('brain_tumor_classifier.h5')

CLASS_NAMES = ['Tumor-Glioma','Tumor-Meningioma','No-tumor','Tumor-Pituitary']

st.title("Brain tumor detection")
st.markdown("Upload an image")

brain_image= st.file_uploader("Choose an image..",type="jpg")
submit= st.button('Predict')

if submit:
    if brain_image is not None:
        file_bytes=np.array(bytearray(brain_image.read()),dtype=np.uint8)
        opencv_image=cv2.imdecode(file_bytes,1)

        st.image(opencv_image, channels="GRAY")
        st.write(opencv_image.shape)

        opencv_image=cv2.resize(opencv_image, (150,150))

        opencv_image.shape=(1,150,150,3)

        Y_pred=model.predict(opencv_image)
        result= CLASS_NAMES[np.argmax(Y_pred)]
        if result == 'Tumor-Pituitary':
            st.title('Benign- ' , result)
        elif result == 'Tumor-Meningioma':
            st.title('Benign- ',result)
        elif result == 'Tumor-Glioma':
            st.title('Malignant- ', result)
        st.title(result)